<a href="https://colab.research.google.com/github/Tejaswi37/2303A51944-Batch-27-/blob/main/Lab3.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
np.random.seed(42)  # for reproducibility
scores = np.random.randint(50, 101, size=(4, 4))
print("Test Scores (4x4 Matrix):\n", scores)


Test Scores (4x4 Matrix):
 [[88 78 64 92]
 [57 70 88 68]
 [72 60 60 73]
 [85 89 73 52]]


In [3]:
row_mean = np.mean(scores, axis=1)
col_mean = np.mean(scores, axis=0)
print("\nRow-wise Means:", row_mean)
print("Column-wise Means:", col_mean)



Row-wise Means: [80.5  70.75 66.25 74.75]
Column-wise Means: [75.5  74.25 71.25 71.25]


In [4]:
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation (overall):", std_dev)
print("Variance (overall):", variance)



Standard Deviation (overall): 12.214073593605043
Variance (overall): 149.18359375


In [5]:
global_max = np.max(scores)
global_min = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)

print("\nGlobal Maximum:", global_max, "at index", max_index)
print("Global Minimum:", global_min, "at index", min_index)




Global Maximum: 92 at index (np.int64(0), np.int64(3))
Global Minimum: 52 at index (np.int64(3), np.int64(3))


In [6]:
median_value = np.median(scores)
print("\nMedian Score:", median_value)



Median Score: 72.5
