<a href="https://colab.research.google.com/github/Tejaswi37/2303A51944-Batch-27-/blob/main/Lab3.2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np.random.seed(10)
image = np.random.randint(0, 256, size=(3, 3, 3))
print("Original RGB Image Matrix:\n", image)



Original RGB Image Matrix:
 [[[  9 125 228]
  [ 15  64 113]
  [123 156 217]]

 [[221 240 157]
  [113 250   8]
  [ 73   0 234]]

 [[ 40 246 164]
  [115  16 100]
  [239 139  54]]]


In [3]:
red_channel = image[:, :, 0]
green_channel = image[:, :, 1]
blue_channel = image[:, :, 2]

print("\nRed Channel:\n", red_channel)
print("\nGreen Channel:\n", green_channel)
print("\nBlue Channel:\n", blue_channel)



Red Channel:
 [[  9  15 123]
 [221 113  73]
 [ 40 115 239]]

Green Channel:
 [[125  64 156]
 [240 250   0]
 [246  16 139]]

Blue Channel:
 [[228 113 217]
 [157   8 234]
 [164 100  54]]


In [4]:
avg_red = np.mean(red_channel)
avg_green = np.mean(green_channel)
avg_blue = np.mean(blue_channel)

print("\nAverage Intensities → Red:", avg_red, "Green:", avg_green, "Blue:", avg_blue)



Average Intensities → Red: 105.33333333333333 Green: 137.33333333333334 Blue: 141.66666666666666


In [5]:
brightened_image = np.clip(image + 50, 0, 255)
print("\nBrightened Image Matrix:\n", brightened_image)




Brightened Image Matrix:
 [[[ 59 175 255]
  [ 65 114 163]
  [173 206 255]]

 [[255 255 207]
  [163 255  58]
  [123  50 255]]

 [[ 90 255 214]
  [165  66 150]
  [255 189 104]]]


In [6]:
print("\nPixel Difference After Brightness Increase:\n", brightened_image - image)


Pixel Difference After Brightness Increase:
 [[[50 50 27]
  [50 50 50]
  [50 50 38]]

 [[34 15 50]
  [50  5 50]
  [50 50 21]]

 [[50  9 50]
  [50 50 50]
  [16 50 50]]]
